name: qualnotes
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter: 
    sdk: flutter
  get: 4.6.5
  firebase_core: ^1.20.1
  firebase_auth: ^3.4.2
  cloud_firestore: ^3.4.4
  google_sign_in: ^5.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
dev_dependencies: 
  build_runner: ^2.2.0
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter
  hive_generator: ^1.1.3

flutter: 
  uses-material-design: true

